"""
Run on M2 to load keys from the USB file generated by generate_keys.py.
M2 encrypts with key_b and decrypts with key_a (opposite of M1).

Usage:
    python3 load_keys.py /path/to/usb/taskapp_keys.txt
"""
import sys
import keyring

KEYRING_SVC = 'taskapp'

def main():
    if len(sys.argv) != 2:
        print('Usage: python3 load_keys.py /path/to/usb/taskapp_keys.txt')
        sys.exit(1)

    key_file = sys.argv[1]

    keys = {}
    with open(key_file, 'r') as f:
        for line in f:
            line = line.strip()
            if '=' in line:
                name, val = line.split('=', 1)
                keys[name.strip()] = val.strip()

    if 'key_a' not in keys or 'key_b' not in keys:
        print('Invalid key file — expected key_a and key_b entries.')
        sys.exit(1)

    existing = keyring.get_password(KEYRING_SVC, 'encrypt_key')
    if existing:
        print('Keys already exist in keyring. Aborting to avoid overwrite.')
        sys.exit(1)

    # M2 is the mirror of M1: encrypt with key_b, decrypt with key_a
    keyring.set_password(KEYRING_SVC, 'encrypt_key', keys['key_b'])
    keyring.set_password(KEYRING_SVC, 'decrypt_key', keys['key_a'])

    print('Keys loaded into M2 keyring.')
    print()
    print('IMPORTANT: shred the key file from the USB now:')
    print(f'  shred -u {key_file}')

if __name__ == '__main__':
    main()
